poll/urls.py
from django.conf.urls import url
from . import views


app_name = 'poll'
urlpatterns = [
	# will look like: /poll/
	url(r'^$', views.IndexView.as_view(), name='index'),
	# will look like: /poll/5/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	# will look like: /poll/5/results/
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	# will look like: /poll/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

website1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^poll/', include('poll.urls')),
    url(r'^admin/', admin.site.urls),
]

poll/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

@python_2_unicode_compatible
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

poll/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
	template_name = 'poll/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'poll/detail.html'

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'poll/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(
			pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form
		return render(request, 'poll/detail.html', {
			'question': question, 
			'error_message': "You did not select a choice.",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(
			reverse('poll:results', args = (question.id,)))

poll/templates/poll/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'poll/detail.css' %}" />

<div id='outer_div'>
	<div id='inner_div'>
		<h3>{{ question.question_text }}</h3>
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		<form action="{% url 'poll:vote' question.id %}" method="post">{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
		{% endfor %}
			<br>
			<input type="submit" value="Vote!" id="vote_button" />
		</form>
	</div>
</div>

poll/templates/poll/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'poll/style.css' %}" />

<div id='outer_div'>
<div id='inner_div'>
	<h3>POLL QUESTIONS</h3>
{% if latest_question_list %}
	<ol>
	{% for question in latest_question_list %}
		<li><a href="/poll/{{ question.id }}/">{{ question.question_text }}</a></li>
	{% endfor %}
	</ol>
{% else %}
	<p>No polls are available.</p>
{% endif %}
</div>
</div>

poll/templates/poll/results.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'poll/results.css' %}" />


<div id='outer_div'>
	<div id='inner_div'>
		<h3>{{ question.question_text }}</h3>

		<ul>
		{% for choice in question.choice_set.all %}
			<li>{{ choice.choice_text }}<br><div id="number_of_votes">{{ choice.votes }} vote{{ choice.votes|pluralize }}</div></li>
		{% endfor %}
		</ul>

		<button><a href="{% url 'poll:detail' question.id %}">Vote again?</a></button>
		<button><a href="{% url 'poll:index' %}">Or check out the other questions!</a></button>
	</div>
</div>

<footer>

</footer>